services:
#    kit_crypt.example:
#        class: Kit\SoarBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    kit_soar.soar:
        class: Kit\SoarBundle\Service\SoarService
        arguments: ["%kit_soar.clients%"]